CREATE TABLE IF NOT EXISTS F_StoreBusinessDate (
    id BIGINT IDENTITY(1,1)  NOT NULL,  
    BusinessDate TIMESTAMP WITHOUT TIME ZONE NULL,
    StoreNo INTEGER NULL,
    PosClose TIMESTAMP WITHOUT TIME ZONE NULL,
    MrmsClose TIMESTAMP WITHOUT TIME ZONE NULL,
    LastBusinessDate TIMESTAMP WITHOUT TIME ZONE NULL,
    LastPosClose TIMESTAMP WITHOUT TIME ZONE NULL,
    LastMrmsClose TIMESTAMP WITHOUT TIME ZONE NULL,
    PRIMARY KEY (id) 
    );

COMMIT;
