CREATE TABLE IF NOT EXISTS public.ICSS_ADJ_CASH_ITEM(
    KHSTOR INTEGER NULL,
    KHSADT INTEGER NULL,
    KHCURR varchar(10) NULL,
    KHMAJT varchar(2) NULL,
    KHSUBT varchar(4) NULL,
    KHITAM decimal(18,2) NULL,
    KHSEQ INTEGER NULL,
    UPDT INTEGER NULL,
    UPTM INTEGER NULL,
    CreateDate TIMESTAMP WITHOUT TIME ZONE NULL
);

commit;