CREATE TABLE IF NOT EXISTS public.ICSS_ADJ_BANK_DEPOSIT(
    KGSTOR INTEGER NULL,
    KGSADT INTEGER NULL,
    KGCURR varchar(10) NULL,
    KGBKAC INTEGER NULL,
    KGCHEQ varchar(1) NULL,
    KGDPAM decimal(18,2) NULL,
    KGDPDT INTEGER NULL,
    KGSEQ INTEGER NULL,
    KGUPDT INTEGER NULL,
    KGUPTM INTEGER NULL,
    KGUSER varchar(30) NULL,
    CreateDate TIMESTAMP WITHOUT TIME ZONE NULL
);

commit;
