CREATE TABLE IF NOT EXISTS public.T_StoreBusinessDate(
    businessdate TIMESTAMP WITHOUT TIME ZONE NULL,
    storeNo VARCHAR(400) NULL,
    posclose TIMESTAMP WITHOUT TIME ZONE NULL,
    mrmsclose TIMESTAMP WITHOUT TIME ZONE NULL,
    LastBusinessDate TIMESTAMP WITHOUT TIME ZONE NULL,
    LastPosclose TIMESTAMP WITHOUT TIME ZONE NULL,
    LastMrmsClose TIMESTAMP WITHOUT TIME ZONE NULL
);

COMMIT;

